[2022-09-05 12:04:23,647] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 12:04:23,697] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 12:04:23,698] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:04:23,698] {taskinstance.py:1043} INFO - Starting attempt 5 of 6
[2022-09-05 12:04:23,699] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:04:23,755] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): insert_dim_date> on 2022-09-04T00:00:00+00:00
[2022-09-05 12:04:23,764] {standard_task_runner.py:52} INFO - Started process 11592 to run task
[2022-09-05 12:04:23,785] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'insert_dim_date', '2022-09-04T00:00:00+00:00', '--job-id', '174', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpbgk9kd30', '--error-file', '/tmp/tmplblxpodx']
[2022-09-05 12:04:23,796] {standard_task_runner.py:77} INFO - Job 174: Subtask insert_dim_date
[2022-09-05 12:04:23,921] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.insert_dim_date 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 12:04:24,002] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=insert_dim_date
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 12:04:24,019] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 12:04:24,053] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 12:04:24,090] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 12:04:24,154] {taskinstance.py:1455} ERROR - duplicate key value violates unique constraint "dim_date_pkey"
DETAIL:  Key (id)=(20200917) already exists.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/dim_date.py", line 9, in main_date
    insert_dwh_table(df)
  File "/opt/airflow/dags/usecase/dim_date.py", line 82, in insert_dwh_table
    cursor.execute(sql, tuple(row))
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "dim_date_pkey"
DETAIL:  Key (id)=(20200917) already exists.

[2022-09-05 12:04:24,164] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=insert_dim_date, execution_date=20220904T000000, start_date=20220905T120423, end_date=20220905T120424
[2022-09-05 12:04:24,238] {local_task_job.py:146} INFO - Task exited with return code 1
