[2022-09-05 05:15:49,303] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 05:15:49,359] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 05:15:49,360] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 05:15:49,361] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 05:15:49,362] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 05:15:49,403] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 05:15:49,409] {standard_task_runner.py:52} INFO - Started process 340 to run task
[2022-09-05 05:15:49,416] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '127', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_postgres.py', '--cfg-path', '/tmp/tmp5tx0iur_', '--error-file', '/tmp/tmpl7tg6vcy']
[2022-09-05 05:15:49,426] {standard_task_runner.py:77} INFO - Job 127: Subtask create_table
[2022-09-05 05:15:49,623] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_postgres.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 05:15:49,821] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 05:15:49,839] {taskinstance.py:1455} ERROR - name 'hook' is not defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_with_postgres.py", line 20, in postgres_to_s3
    conn = hook.get_conn()
NameError: name 'hook' is not defined
[2022-09-05 05:15:49,876] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres, task_id=create_table, execution_date=20220904T000000, start_date=20220905T051549, end_date=20220905T051549
[2022-09-05 05:15:50,176] {local_task_job.py:146} INFO - Task exited with return code 1
