[2022-09-05 06:55:20,661] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 06:55:20,709] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 06:55:20,710] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 06:55:20,710] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 06:55:20,711] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 06:55:20,758] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 06:55:20,763] {standard_task_runner.py:52} INFO - Started process 2390 to run task
[2022-09-05 06:55:20,769] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '144', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmp71errrzp', '--error-file', '/tmp/tmpoics2dxx']
[2022-09-05 06:55:20,772] {standard_task_runner.py:77} INFO - Job 144: Subtask create_table
[2022-09-05 06:55:20,874] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 06:55:20,969] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 06:55:20,983] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: 172.17.0.1, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 06:55:21,109] {python.py:118} INFO - Done. Returned value was: None
[2022-09-05 06:55:21,166] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T065520, end_date=20220905T065521
[2022-09-05 06:55:21,256] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 06:55:21,304] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-09-05 07:00:34,581] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:00:34,631] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:00:34,632] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:00:34,632] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 07:00:34,633] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:00:34,670] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:00:34,674] {standard_task_runner.py:52} INFO - Started process 2602 to run task
[2022-09-05 07:00:34,679] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '145', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmp48wiwfin', '--error-file', '/tmp/tmpi8gl9c3v']
[2022-09-05 07:00:34,682] {standard_task_runner.py:77} INFO - Job 145: Subtask create_table
[2022-09-05 07:00:34,776] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:00:34,866] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:00:34,878] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:00:35,605] {taskinstance.py:1455} ERROR - relation "customers" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 46, in create_table
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "customers" does not exist

[2022-09-05 07:00:35,614] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T070034, end_date=20220905T070035
[2022-09-05 07:00:35,695] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 07:03:03,381] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:03:03,422] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:03:03,423] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:03:03,424] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 07:03:03,424] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:03:03,461] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:03:03,465] {standard_task_runner.py:52} INFO - Started process 2699 to run task
[2022-09-05 07:03:03,471] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '146', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpgriir_rd', '--error-file', '/tmp/tmptxwhxe1e']
[2022-09-05 07:03:03,474] {standard_task_runner.py:77} INFO - Job 146: Subtask create_table
[2022-09-05 07:03:03,601] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:03:03,696] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:03:03,709] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:03:04,362] {taskinstance.py:1455} ERROR - relation "customers" does not exist
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 46, in create_table
    cursor.execute(sql)
psycopg2.errors.UndefinedTable: relation "customers" does not exist

[2022-09-05 07:03:04,373] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T070303, end_date=20220905T070304
[2022-09-05 07:03:04,445] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 07:09:35,591] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:09:35,691] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:09:35,692] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:09:35,693] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 07:09:35,694] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:09:35,749] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:09:35,756] {standard_task_runner.py:52} INFO - Started process 2901 to run task
[2022-09-05 07:09:35,765] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '147', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpv77nlhpn', '--error-file', '/tmp/tmpnj4ff162']
[2022-09-05 07:09:35,770] {standard_task_runner.py:77} INFO - Job 147: Subtask create_table
[2022-09-05 07:09:35,879] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:09:35,987] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:09:36,004] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:09:36,628] {python.py:118} INFO - Done. Returned value was: None
[2022-09-05 07:09:36,687] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T070935, end_date=20220905T070936
[2022-09-05 07:09:36,770] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 07:09:36,819] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-09-05 07:24:00,983] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:24:01,135] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:24:01,137] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:24:01,137] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 07:24:01,138] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:24:01,188] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:24:01,192] {standard_task_runner.py:52} INFO - Started process 3328 to run task
[2022-09-05 07:24:01,203] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '148', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmp016eidvp', '--error-file', '/tmp/tmpbcnbyaj3']
[2022-09-05 07:24:01,207] {standard_task_runner.py:77} INFO - Job 148: Subtask create_table
[2022-09-05 07:24:01,316] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:24:01,418] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:24:01,434] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:24:01,896] {python.py:118} INFO - Done. Returned value was: None
[2022-09-05 07:24:01,944] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T072400, end_date=20220905T072401
[2022-09-05 07:24:02,044] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 07:24:02,055] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-09-05 07:26:01,548] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:26:01,596] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:26:01,597] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:26:01,597] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 07:26:01,598] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:26:01,632] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:26:01,637] {standard_task_runner.py:52} INFO - Started process 3390 to run task
[2022-09-05 07:26:01,643] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpihy7p5o7', '--error-file', '/tmp/tmpgi0vday_']
[2022-09-05 07:26:01,648] {standard_task_runner.py:77} INFO - Job 149: Subtask create_table
[2022-09-05 07:26:01,762] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:26:01,877] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:26:01,894] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:26:01,954] {python.py:118} INFO - Done. Returned value was: None
[2022-09-05 07:26:02,020] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T072601, end_date=20220905T072602
[2022-09-05 07:26:02,163] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 07:26:02,176] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-09-05 10:52:24,810] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:52:24,876] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:52:24,877] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:52:24,877] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 10:52:24,878] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:52:24,918] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 10:52:24,924] {standard_task_runner.py:52} INFO - Started process 9441 to run task
[2022-09-05 10:52:24,930] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpd95av9l4', '--error-file', '/tmp/tmpmvvzopd4']
[2022-09-05 10:52:24,934] {standard_task_runner.py:77} INFO - Job 152: Subtask create_table
[2022-09-05 10:52:25,057] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 10:52:25,165] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 10:52:25,200] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 10:52:25,213] {taskinstance.py:1455} ERROR - name 'pd' is not defined
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 5, in main
    df_ops = select_ops_table()
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 20, in select_ops_table
    df = pd.read_sql(sql, conn)
NameError: name 'pd' is not defined
[2022-09-05 10:52:25,260] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T105224, end_date=20220905T105225
[2022-09-05 10:52:25,394] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 10:54:36,192] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:54:36,261] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:54:36,262] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:54:36,262] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 10:54:36,266] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:54:36,348] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 10:54:36,353] {standard_task_runner.py:52} INFO - Started process 9508 to run task
[2022-09-05 10:54:36,358] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '153', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpnpmpjkhh', '--error-file', '/tmp/tmpa6hitgkm']
[2022-09-05 10:54:36,362] {standard_task_runner.py:77} INFO - Job 153: Subtask create_table
[2022-09-05 10:54:36,531] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 10:54:36,657] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 10:54:36,671] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 10:54:36,748] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 10:54:36,756] {taskinstance.py:1455} ERROR - Execution failed on sql '
    select 
        e.id
        ,d.name
    from 
	    dim_customer d 
        ': missing FROM-clause entry for table "e"
LINE 3:         e.id
                ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1681, in execute
    cur.execute(*args, **kwargs)
psycopg2.errors.UndefinedTable: missing FROM-clause entry for table "e"
LINE 3:         e.id
                ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 7, in main
    df_dwh = select_dwh_table()
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 35, in select_dwh_table
    df = pd.read_sql(sql, conn)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 489, in read_sql
    chunksize=chunksize,
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1727, in read_query
    cursor = self.execute(*args)
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/sql.py", line 1693, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql '
    select 
        e.id
        ,d.name
    from 
	    dim_customer d 
        ': missing FROM-clause entry for table "e"
LINE 3:         e.id
                ^

[2022-09-05 10:54:36,767] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T105436, end_date=20220905T105436
[2022-09-05 10:54:36,851] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 11:24:04,909] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:24:04,965] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:24:04,965] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:24:04,966] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 11:24:04,966] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:24:05,002] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 11:24:05,008] {standard_task_runner.py:52} INFO - Started process 10383 to run task
[2022-09-05 11:24:05,012] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '160', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpm1zklzzy', '--error-file', '/tmp/tmp995fjt9p']
[2022-09-05 11:24:05,016] {standard_task_runner.py:77} INFO - Job 160: Subtask create_table
[2022-09-05 11:24:05,131] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 11:24:05,223] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 11:24:05,240] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:24:05,275] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:24:05,308] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:24:05,318] {taskinstance.py:1455} ERROR - syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(id`,`name) VALUES (3923,'Ani')
                                   ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 9, in main
    insert_dwh_table(df)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 53, in insert_dwh_table
    cursor.execute(sql, tuple(row))
psycopg2.errors.SyntaxError: syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(id`,`name) VALUES (3923,'Ani')
                                   ^

[2022-09-05 11:24:05,328] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T112404, end_date=20220905T112405
[2022-09-05 11:24:05,426] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 11:27:40,711] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:27:40,766] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:27:40,767] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:27:40,768] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 11:27:40,768] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:27:40,807] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 11:27:40,812] {standard_task_runner.py:52} INFO - Started process 10495 to run task
[2022-09-05 11:27:40,818] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '161', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmp2bbkh342', '--error-file', '/tmp/tmpdzpqrwku']
[2022-09-05 11:27:40,822] {standard_task_runner.py:77} INFO - Job 161: Subtask create_table
[2022-09-05 11:27:40,947] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 11:27:41,034] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 11:27:41,050] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:27:41,077] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:27:41,100] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:27:41,108] {taskinstance.py:1455} ERROR - syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(`id`,`name`) VALUES (3923,'Ani')
                                 ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 9, in main
    insert_dwh_table(df)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 53, in insert_dwh_table
    cursor.execute(sql, tuple(row))
psycopg2.errors.SyntaxError: syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(`id`,`name`) VALUES (3923,'Ani')
                                 ^

[2022-09-05 11:27:41,117] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T112740, end_date=20220905T112741
[2022-09-05 11:27:41,190] {local_task_job.py:146} INFO - Task exited with return code 1
