[2022-09-05 07:26:38,043] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:26:38,118] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 07:26:38,119] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:26:38,119] {taskinstance.py:1043} INFO - Starting attempt 2 of 3
[2022-09-05 07:26:38,120] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 07:26:38,159] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 07:26:38,165] {standard_task_runner.py:52} INFO - Started process 3407 to run task
[2022-09-05 07:26:38,171] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '150', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmp7uea1q7t', '--error-file', '/tmp/tmpfkc50a77']
[2022-09-05 07:26:38,175] {standard_task_runner.py:77} INFO - Job 150: Subtask create_table
[2022-09-05 07:26:38,286] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 07:26:38,354] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 07:26:38,369] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 07:26:38,385] {taskinstance.py:1455} ERROR - duplicate key value violates unique constraint "products_pkey"
DETAIL:  Key (id)=(477) already exists.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 106, in create_table
    cursor.execute(sql)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "products_pkey"
DETAIL:  Key (id)=(477) already exists.

[2022-09-05 07:26:38,393] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T072638, end_date=20220905T072638
[2022-09-05 07:26:38,466] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 10:56:23,189] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:56:23,250] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 10:56:23,250] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:56:23,251] {taskinstance.py:1043} INFO - Starting attempt 2 of 3
[2022-09-05 10:56:23,252] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 10:56:23,305] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 10:56:23,310] {standard_task_runner.py:52} INFO - Started process 9560 to run task
[2022-09-05 10:56:23,316] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '154', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpl4un41hf', '--error-file', '/tmp/tmpmhhswo_r']
[2022-09-05 10:56:23,321] {standard_task_runner.py:77} INFO - Job 154: Subtask create_table
[2022-09-05 10:56:23,436] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 10:56:23,545] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 10:56:23,570] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 10:56:23,611] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 10:56:23,705] {logging_mixin.py:104} INFO -      id  name
0  3923   Ani
1  3924  Budi
2  3925  Caca    id  name
0   1  budi
[2022-09-05 10:56:23,706] {python.py:118} INFO - Done. Returned value was: None
[2022-09-05 10:56:23,750] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T105623, end_date=20220905T105623
[2022-09-05 10:56:23,841] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-09-05 10:56:23,857] {local_task_job.py:146} INFO - Task exited with return code 0
[2022-09-05 11:29:15,308] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:29:15,372] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 11:29:15,373] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:29:15,373] {taskinstance.py:1043} INFO - Starting attempt 2 of 3
[2022-09-05 11:29:15,373] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 11:29:15,421] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): create_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 11:29:15,426] {standard_task_runner.py:52} INFO - Started process 10542 to run task
[2022-09-05 11:29:15,431] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'efishiery_nomor_satu', 'create_table', '2022-09-04T00:00:00+00:00', '--job-id', '162', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/soal_nomor_satu.py', '--cfg-path', '/tmp/tmpk6p70v_h', '--error-file', '/tmp/tmpxgh4o_ie']
[2022-09-05 11:29:15,437] {standard_task_runner.py:77} INFO - Job 162: Subtask create_table
[2022-09-05 11:29:15,546] {logging_mixin.py:104} INFO - Running <TaskInstance: efishiery_nomor_satu.create_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 11:29:15,629] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=farah
AIRFLOW_CTX_DAG_ID=efishiery_nomor_satu
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 11:29:15,644] {base.py:74} INFO - Using connection to: id: efishery. Host: 172.17.0.1, Port: 5432, Schema: efishery, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:29:15,667] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:29:15,691] {base.py:74} INFO - Using connection to: id: efishery_dwh. Host: 172.17.0.1, Port: 5432, Schema: efishery_dwh, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 11:29:15,700] {taskinstance.py:1455} ERROR - syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(`id`,`name`) VALUES (3923,'Ani')
                                 ^
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 9, in main
    insert_dwh_table(df)
  File "/opt/airflow/dags/usecase/soal_nomor_satu.py", line 53, in insert_dwh_table
    cursor.execute(sql, tuple(row))
psycopg2.errors.SyntaxError: syntax error at or near "`"
LINE 1: INSERT INTO dim_customer(`id`,`name`) VALUES (3923,'Ani')
                                 ^

[2022-09-05 11:29:15,708] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=efishiery_nomor_satu, task_id=create_table, execution_date=20220904T000000, start_date=20220905T112915, end_date=20220905T112915
[2022-09-05 11:29:15,762] {local_task_job.py:146} INFO - Task exited with return code 1
