[2022-09-05 05:47:20,359] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 05:47:20,425] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 05:47:20,427] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 05:47:20,430] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 05:47:20,430] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 05:47:20,472] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 05:47:20,479] {standard_task_runner.py:52} INFO - Started process 965 to run task
[2022-09-05 05:47:20,486] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_v1', 'create_pet_table', '2022-09-04T00:00:00+00:00', '--job-id', '132', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_postgres.py', '--cfg-path', '/tmp/tmpr98cymhy', '--error-file', '/tmp/tmpr8xjux3i']
[2022-09-05 05:47:20,491] {standard_task_runner.py:77} INFO - Job 132: Subtask create_pet_table
[2022-09-05 05:47:20,584] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 05:47:20,683] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v1
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 05:47:20,684] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS test (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          
[2022-09-05 05:47:20,700] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 05:47:20,765] {taskinstance.py:1455} ERROR - could not translate host name "host.docker.internal" to address: Name or service not known
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2022-09-05 05:47:20,769] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v1, task_id=create_pet_table, execution_date=20220904T000000, start_date=20220905T054720, end_date=20220905T054720
[2022-09-05 05:47:20,858] {local_task_job.py:146} INFO - Task exited with return code 1
[2022-09-05 06:18:10,394] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 06:18:10,454] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [queued]>
[2022-09-05 06:18:10,455] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 06:18:10,456] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2022-09-05 06:18:10,456] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 06:18:10,499] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_pet_table> on 2022-09-04T00:00:00+00:00
[2022-09-05 06:18:10,506] {standard_task_runner.py:52} INFO - Started process 1582 to run task
[2022-09-05 06:18:10,517] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_v1', 'create_pet_table', '2022-09-04T00:00:00+00:00', '--job-id', '138', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dags_with_postgres.py', '--cfg-path', '/tmp/tmp3blt0zjz', '--error-file', '/tmp/tmpmtai86w7']
[2022-09-05 06:18:10,525] {standard_task_runner.py:77} INFO - Job 138: Subtask create_pet_table
[2022-09-05 06:18:10,630] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_postgres_v1.create_pet_table 2022-09-04T00:00:00+00:00 [running]> on host 2b8e628fc16c
[2022-09-05 06:18:10,744] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_v1
AIRFLOW_CTX_TASK_ID=create_pet_table
AIRFLOW_CTX_EXECUTION_DATE=2022-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-04T00:00:00+00:00
[2022-09-05 06:18:10,745] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS test (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          
[2022-09-05 06:18:10,765] {base.py:74} INFO - Using connection to: id: postgres_localhost. Host: host.docker.internal, Port: 5432, Schema: test, Login: airflow, Password: XXXXXXXX, extra: None
[2022-09-05 06:18:10,791] {taskinstance.py:1455} ERROR - could not translate host name "host.docker.internal" to address: Name or service not known
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/operators/postgres.py", line 71, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.internal" to address: Name or service not known

[2022-09-05 06:18:10,794] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_v1, task_id=create_pet_table, execution_date=20220904T000000, start_date=20220905T061810, end_date=20220905T061810
[2022-09-05 06:18:10,890] {local_task_job.py:146} INFO - Task exited with return code 1
